// File location: apps/control-panel/lib/agents/script-doctor.ts

import Anthropic from "@anthropic-ai/sdk";
// (These database functions would be imported from your Neon Postgres helper file)
import { getConcept, updateConceptTreatment, createGateApproval, logAgentRun } from "../db"; 

const anthropic = new Anthropic({
  apiKey: process.env.ANTHROPIC_API_KEY,
});

export interface ScriptDoctorResult {
  doctor_notes: string;
  structural_score: number;
  revised_treatment: string;
}

// ---------------------------------------------------------
// 1. THE SYSTEM PROMPT (Hardcoded as a string variable)
// ---------------------------------------------------------
const SCRIPT_DOCTOR_PROMPT = `
You are a master Hollywood Script Doctor and Narrative Strategist. Your job is to take a raw concept/treatment generated by a junior writer and perform a structural and prose pass to elevate it to premium studio quality.

PROJECT BIBLE / CONSTRAINTS:
1. You may NOT invent new world-building lore, new primary characters, or new underlying ideologies. You must strictly adhere to the provided canonical elements.
2. Focus strictly on narrative structure, pacing, thematic resonance, and elevating the prose to be visceral and cinematic.
3. Eliminate passive voice and cliché plot tropes.

FINALIZING THE SCRIPT:
You must output a single, valid JSON object wrapped in a markdown code block (using triple backticks and the word json) containing the following exact keys:
- "doctor_notes": (string) A brief, candid paragraph explaining what was weak.
- "structural_score": (integer 1-10) Your assessment of the new pacing.
- "revised_treatment": (string) The complete, polished, elevated treatment.
`;

// ---------------------------------------------------------
// 2. THE EXECUTION FUNCTION (Triggered by your app)
// ---------------------------------------------------------
export async function runScriptDoctor(conceptId: string, projectBibleText: string) {
  const startTime = Date.now();
  
  // A. Fetch the raw draft from the database
  const concept = await getConcept(conceptId);
  if (!concept) throw new Error("Concept not found in Studio OS.");

  // B. Build the user message dynamically
  const userMessage = `
  Here is the Project Bible: ${projectBibleText}
  Here is the raw treatment to fix: ${concept.raw_treatment}
  `;

  try {
    // C. Fire the prompt to Claude!
    // Notice how `system` uses the variable we defined at the top of the file
    const response = await anthropic.messages.create({
      model: "claude-sonnet-4-6",
      max_tokens: 4000,
      system: SCRIPT_DOCTOR_PROMPT, 
      messages: [{ role: "user", content: userMessage }],
    });

    const replyText = response.content[0].text;
    
    // D. Extract and parse the JSON
    const jsonMatch = replyText.match(/```json\n([\s\S]*?)\n```/);
    if (!jsonMatch) throw new Error("Script Doctor failed to return valid JSON.");
    
    const parsed: ScriptDoctorResult = JSON.parse(jsonMatch[1]);

    // E. Save to Neon DB and open a Human Gate
    await updateConceptTreatment(conceptId, parsed.revised_treatment, parsed.doctor_notes);
    
    await logAgentRun({
      agent: "Script Doctor",
      conceptId,
      tokens: response.usage.total_tokens,
      latency_ms: Date.now() - startTime,
    });

    const gateId = await createGateApproval({
      conceptId,
      gateType: "G1", 
      requiredRole: "Creative Director",
      status: "pending"
    });

    return { ok: true, gateId, notes: parsed.doctor_notes };

  } catch (error) {
    console.error("Script Doctor Agent Error:", error);
    return { ok: false, error: "Agent execution failed." };
  }
}